version: 2

sources:
  - name: staging
    database: useful-monitor-415110
    schema: trips_data_all

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: external_fhv_data
